local config = require("leaf.config")

describe("leaf.config", function()
  before_each(function()
    config.setup({})
  end)

  it("applies documented defaults", function()
    assert.are.same(true, config.options.interactive)
    assert.are.same("auto", config.options.position)
    assert.are.same("rounded", config.options.border)
    assert.are.same(0.5, config.options.split_ratio)
    assert.are.same(3, config.options.scroll_lines)
    assert.are.same(true, config.options.show_hints)
    assert.is_nil(config.options.leaf_path)
  end)

  it("deep-merges user opts over defaults", function()
    config.setup({ interactive = true, width_ratio = 0.9 })
    assert.are.same(true, config.options.interactive)
    assert.are.same(0.9, config.options.width_ratio)
    assert.are.same(0.7, config.options.height_ratio)
  end)

  it("falls back to auto on an invalid position", function()
    config.setup({ position = "underneath" })
    assert.are.same("auto", config.options.position)
  end)

  it("accepts tab as a valid position", function()
    config.setup({ position = "tab" })
    assert.are.same("tab", config.options.position)
  end)

  describe("executable resolution", function()
    it("returns nil for an unrunnable explicit leaf_path", function()
      config.setup({ leaf_path = "/nonexistent/leaf" })
      assert.is_nil(config.executable())
    end)

    it("accepts a runnable explicit leaf_path", function()
      config.setup({ leaf_path = "/bin/true" })
      assert.are.same("/bin/true", config.executable())
    end)

    it("resolves leaf from $PATH by default", function()
      assert.are.same(vim.fn.exepath("leaf"), config.executable())
    end)
  end)

  describe("markdown detection", function()
    it("matches known filetypes and rejects others", function()
      assert.is_true(config.is_markdown_ft("markdown"))
      assert.is_true(config.is_markdown_ft("markdown.gfm"))
      assert.is_false(config.is_markdown_ft("lua"))
    end)

    it("matches known extensions case-insensitively", function()
      assert.is_true(config.is_markdown_ext("README.MD"))
      assert.is_true(config.is_markdown_ext("doc.markdown"))
      assert.is_false(config.is_markdown_ext("init.lua"))
    end)
  end)
end)
